### ISSUE TITLE
Value field breaks when options passed as object instead of listed on view

### ISSUE THREAD

**Issue by clottman** [cosminstefanxp/bootstrap-slider-knockout-binding#14]
The plugin seems to only work if you list all properties on the view, instead of providing an options object which is defined in the viewmodel. Since I'm using Typescript for my viewmodels, it's important for me to define data/options on the viewmodel where they are clearly visible and strongly typed. 
[Repro of issue](https://jsfiddle.net/ERz7u/52/) - See console error as well as failure to update slider value observable

**Comment by cosminstefanxp** [comment]
Thanks for the report and the fix. I've merged it in.
